Online_Food_Ordering/Online_Food_Ordering/urls.py
from django.contrib import admin
from django.urls import path, include
from ordering.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ordering/', include("ordering.urls")),
    path('', index) # test
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Online_Food_Ordering/ordering/urls.py
from django.urls import path
from . import views
app_name = "ordering"
urlpatterns = [
    path("", views.index, name="index"),
    path("cart", views.cart, name="cart"),
    path("add", views.add, name="add"),
    path("login", views.login, name ="login"),
    path("logout", views.logout, name = "logout"),
    path("register", views.register, name = "register"),
    path("clear_cart", views.clear_cart, name = "clear_cart"),
    path("delete_item", views.delete_item, name = "delete_item"),
    path("confirm_order", views.confirm_order, name = "confirm_order"),
    path("orders", views.orders, name = "orders"),
    path("delete_order", views.delete_order, name = "delete_order"),
    path("profile", views.profile, name = "profile")
]

Online_Food_Ordering/ordering/models.py
from django.db import models
# Create your models here.

class Food(models.Model):
    name = models.CharField(max_length=64)
    image = models.ImageField(upload_to = "images/")
    price = models.FloatField()

    def __str__(self):
        return f"{self.name}/{self.price}"

class User(models.Model):
    id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=64)
    def __str__(self):
        return f"{self.username}"

class Order_User(models.Model):
    order_id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.CharField(max_length=10, default="")
    total = models.FloatField(default=0)
    def __str__(self):
        return f"{self.order_id}-{self.user}"

class Order(models.Model):
    order = models.ForeignKey(Order_User, on_delete=models.CASCADE)
    food = models.ForeignKey(Food , on_delete=models.CASCADE)
    quantity = models.IntegerField()
    def __str__(self):
        return f"{self.order}--{self.food}--{self.quantity}"

Online_Food_Ordering/ordering/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import *
from datetime import datetime as d

food_data = Food.objects.all()
# index
def index(request):
    user_name = request.session.get("user_name", "guest")
    return render(request, "ordering/index.html", {"data": food_data, "user": user_name})

def add(request):
    if request.session.get("user_id") == None:
        messages.error(request, 'Please, login.')
        return HttpResponseRedirect("/")
    if request.method == "POST":
        # check if that item already exists in the cart
        added = False
        cart_data = request.session["cart_data"]
        for item in cart_data:
            if item[0] == request.POST["food_id"]:
                item[2] += int(request.POST["food_quantity"])
                request.session["cart_data"] = cart_data
                added = True
                break
        if not added:
            request.session["cart_data"] += [(request.POST["food_id"], request.POST["food_name"], int(request.POST['food_quantity']), float(request.POST['food_price']))]
        messages.success(request, 'Item has been added to the cart.')
    return HttpResponseRedirect("/")

# cart
def cart(request):
    if request.session.get("user_id") == None:
        messages.error(request, 'Please, login.')
        return HttpResponseRedirect("/")
    if request.session["cart_data"] == []:
        messages.error(request, "The cart is empty")
        return HttpResponseRedirect("/")
    mockup = [(item[0], item[1], f"{item[2]}x{item[3]}", f"{item[2]*item[3]}฿") for item in request.session["cart_data"]]
    total = sum(int(x[2])*float(x[3]) for x in request.session["cart_data"])
    user_name = request.session.get("user_name", "guest")
    return render(request, "ordering/cart.html", {"data": mockup, "total": total, "user":user_name})

def clear_cart(request):
    request.session["cart_data"] = []
    return HttpResponseRedirect(reverse("ordering:cart"))

def delete_item(request):
    if request.method == "POST":
        cart_data = request.session["cart_data"]
        for index, item in enumerate(cart_data):
            if item[0] == request.POST["food_id"]:
                cart_data.pop(index)
                request.session["cart_data"] = cart_data
                break
    return HttpResponseRedirect(reverse("ordering:cart"))

def confirm_order(request):
    # Order_User table
    total = sum(x[2]*x[3] for x in request.session["cart_data"])
    user = User.objects.get(id=request.session["user_id"])
    entry = Order_User(order_id = d.now().strftime("%y%m%d%H%M%S"), user=user, date=d.now().strftime("%d-%m-%y"), total=total)
    entry.save()
    # Order table
    for item in request.session["cart_data"]:
        food = Food.objects.get(id=item[0])
        quantity = item[2]
        order = Order(order=entry, food=food, quantity=quantity)
        order.save()
    request.session["cart_data"] = []
    messages.success(request,"Confirmed!")
    return HttpResponseRedirect("/")

# orders page
def orders(request):
    if request.session.get("user_id") == None:
        messages.error(request, 'Please, login.')
        return HttpResponseRedirect("/")
    user = User.objects.get(id=request.session["user_id"])
    order_list = Order_User.objects.filter(user=user)
    # use Order_User objects to search in order table
    order_data = []
    for order in order_list:
        item_list = Order.objects.filter(order=order) # get specific rows that match the order_id
        mockup = [(i.food.name, f"{i.quantity}x{i.food.price}", f"{int(i.quantity)*float(i.food.price)}฿") for i in item_list]
        order_data += [(order.order_id, order.date, order.total, mockup)]
    user_name = request.session.get("user_name", "guest")
    return render(request, "ordering/orders.html", {"data": order_data, "user":user_name})

def delete_order(request):
    if request.method == "POST":
        Order_User.objects.filter(order_id=request.POST["order_id"]).delete()
        messages.success(request, "The order has been deleted.")
    return HttpResponseRedirect(reverse("ordering:orders"))

# login
def login(request):
    if request.method == "POST":
        try: 
            user_data = User.objects.get(username = request.POST["username"], password = request.POST["password"])
            request.session["user_name"] = user_data.username
            request.session["user_id"] = user_data.id
            request.session["cart_data"] = []
            messages.success(request, "login สำเร็จ")
        except:
            messages.error(request, "login ไม่สำเร็จ")
        return HttpResponseRedirect("/")
    return render(request, "ordering/login.html")

def logout(request):
    request.session.pop("user_name")
    request.session.pop("user_id")
    request.session.pop("cart_data")
    return HttpResponseRedirect("/")

def register(request):
    if request.method == "POST":
        try:
            user_data = User.objects.get(username = request.POST["reguser"])
        except:
            user_data = None
        if user_data:
            messages.error(request,"ซ้ำ")
        else:
            if request.POST['reguser'] == 'guest':
                messages.error(request,"ซ้ำ")
            else:
                reg = User.objects.create(username = request.POST['reguser'],password = request.POST['regpassword'])
                messages.success(request,"สมัครสำเร็จ")
        return HttpResponseRedirect("/")
    return render(request, "ordering/register.html")

# profile
def profile(request):
    if request.session.get("user_id") == None:
        messages.error(request, 'Please, login.')
        return HttpResponseRedirect("/")
    if request.method == "POST":
        if request.POST["new-password"] == request.POST["confirm-password"]:
            user = User.objects.get(id=request.session["user_id"])
            user.password = request.POST["new-password"]
            user.save()
            messages.success(request, "You have changed your password.")
        else:
            messages.error(request, "Something went wrong.")
        return HttpResponseRedirect("/")
    user_name = request.session.get("user_name", "guest")
    return render(request, "ordering/profile.html", {"user":user_name})

Online_Food_Ordering/ordering/templates/ordering/cart.html
{% extends "ordering/layout.html" %}
{% load static %} 
{% block body %}
    <link href="/static/ordering/cart_style.css?{% now 'U' %}" rel="stylesheet">
    <h1> Cart </h1>
        <ol>
            {% for item in data %}
                <li>{{item.1}} {{item.2}} {{item.3}} 
                    <form action="{%url 'ordering:delete_item'%}" method="post"  style="display: inline;">{%csrf_token%}
                        <input type="hidden" name="food_id" value="{{item.0}}">
                        <input type="submit" value="delete">
                    </form>
                </li>
            {% endfor %}
            <li>Total = {{total}}฿</li>
        </ol>
<a href="{%url 'ordering:clear_cart'%}">clear cart</a>
<p><form action="{%url 'ordering:confirm_order'%}" method="post">{%csrf_token%}
    <input type="submit" value="Confirm">
</form></p>
{% endblock %}

Online_Food_Ordering/ordering/templates/ordering/index.html
{% extends "ordering/layout.html" %}
{% load static %} 
{% block body %}
    <link href="/static/ordering/index_style.css?{% now 'U' %}" rel="stylesheet">
    <h1> hello, {{user}}</h1>
    <div class="table">
        <table> 
            <tr>
                <th>Name</th>
                <th>Image</th>
                <th>Price</th>
                <th>Quantity</th>
            </tr>
            {% for food in data %}
                <tr>
                    <td>{{food.name}}</td>
                    <td class="img-col"> <img src="{{MEDIA_URL}}{{food.image}}" style="width:200px;height:200px;"> </td>
                    <td>{{food.price}}</td>
                    <td class="form-col">
                        <form action="{%url 'ordering:add'%}" method="post">
                            {%csrf_token%}
                            <input type="hidden" name="food_id" value="{{food.id}}">
                            <input type="hidden" name="food_name" value="{{food.name}}">
                            <input type="hidden" name="food_img" value="{{food.image}}">
                            <input type="hidden" name="food_price" value="{{food.price}}">
                            <input type="number" name="food_quantity" min="1" placeholder="quantity" required>
                            <input type="submit" value="add">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

Online_Food_Ordering/ordering/templates/ordering/layout.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="/static/ordering/layout_style.css?{% now 'U' %}" rel="stylesheet">
    <title>Online Food Ordering</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
        {% endfor %}
    {% endif %}
    <div class="container">
        <div class="header">
            <h1><a id = "profile" href="{%url 'ordering:profile'%}">{{user}}</a></h1>
            {% if user != "guest" %}
                <a id="logout" href="/ordering/logout">logout</a>
            {% else %}
                <a id="login" href="/ordering/login">login</a>
                <a id="register" href="/ordering/register">register</a>
            {% endif %}
            <div class="sidebar"> 
                <ul class="nav">
                    <li><a href="{%url 'ordering:index'%}"><p>Store</p></a></li>
                    <li><a href="{%url 'ordering:cart'%}"><p>Cart</p></a></li>
                    <li><a href="{%url 'ordering:orders'%}"><p>Orders</p></a></li>
                </ul>
            </div>
        </div>
        <div class="content">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

Online_Food_Ordering/ordering/templates/ordering/login.html
{% load static %}
{% block body %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/ordering/login_style.css?{% now 'U' %}" rel="stylesheet">
    <title>login</title>
</head>

<body style="background-color: red;">
    <form action="login" method="post">
        {% csrf_token %}
        <div class="login-content">
            <h1>Login</h1>
            <p>username</p>
            <input type="text" name="username" required>
            <p>password</p>
            <input type="password" name="password" required>
            <br>
            <br>
            <input type="submit">
        </div>
    </form>
</body>

</html>
{% endblock %}

Online_Food_Ordering/ordering/templates/ordering/orders.html
{% extends "ordering/layout.html" %}
{% load static %} 
{% block body %}
    <link href="/static/ordering/orders_style.css?{% now 'U' %}" rel="stylesheet">
    <h1> Orders </h1>
    {% for order in data %}
        <h2> #{{order.0}}</h2>
        <h3> {{order.1}} </h3>
            <ol>
                {% for item in order.3 %}
                    <li>{{item.0}} {{item.1}} {{item.2}} </li>
                {% endfor %}
                <li>Total = {{order.2}}฿</li>
            </ol>
        <form action="{%url 'ordering:delete_order'%}" method="post">
            {%csrf_token%}
            <input type="hidden" name="order_id" value="{{order.0}}">
            <input type="submit" value="delete">
        </form>
    {% endfor %}
{% endblock %}

Online_Food_Ordering/ordering/templates/ordering/profile.html
{% load static %}
{% block body %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/ordering/profile_style.css?{% now 'U' %}" rel="stylesheet">
    <title>login</title>
</head>

<body style="background-color: red;">
    <form action="{%url 'ordering:profile'%}" method="post">
        {% csrf_token %}
        <div class="profile-content">
            <h1>Profile</h1>
            <p>username</p>
            <input id="username" type="text" name="username" value="{{user}}" readonly>
            <p>new password</p>
            <input type="password" name="new-password">
            <p>confirm password</p>
            <input type="password" name="confirm-password">
            <br>
            <br>
            <input type="submit" value="save">
        </div>
    </form>
</body>

</html>
{% endblock %}

Online_Food_Ordering/ordering/templates/ordering/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/ordering/register_style.css?{% now 'U' %}" rel="stylesheet">
    <title>Register</title>
</head>

<body style="background-color:red ;">
    <form action="register" method="post">
        {% csrf_token %}
        <div class="register-content">
            <h1>Register</h1>
            <p>username</p>
            <input type="text" name="reguser" required>
            <p>password</p>
            <input type="password" name="regpassword" id="password" required>
            <br>
            <p>confirm password</p>
            <input type="password" id="confirmPassword" required>
            <br>
            <br>
            <input type="submit" id="submitBtn">
        </div>
    </form>
    
</body>
<script>
    password = document.getElementById("password")
    confirmPassword = document.getElementById("confirmPassword")
    submitBtn = document.getElementById("submitBtn")

    submitBtn.addEventListener("click",(event) => {
        console.log(password);
        if(password.value !== confirmPassword.value){
            alert("password ไม่ตรง")
            event.preventDefault()
        } 
    })
</script>
</html>